version: '3'

services:

  app:
    restart: always
    build: ./app
    environment:
      - DATABASE_URI=postgres://testing:testing@postgres:5432/testing
    volumes:
      - ./app:/app
    links:
      - postgres
    ports:
      - "5000:5000"

  json:
    restart: always
    image: python:3.7.5-slim
    volumes:
      - ./json:/json
    ports:
      - "8000:8000"
    command: "python -m  http.server -d /json "

  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=testing
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
